{% set name = "nghttp2" %}
{% set version = "1.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nghttp2/{{ name }}/releases/download/v{{ version }}/nghttp2-{{ version }}.tar.gz
  sha256: 45cc3ed91966551f92b31958ceca9b3a9f23ce4faf5cbedb78aa3327cd4e5907

build:
{% if bootstrapping == 'yes' %}
  # Please increment by two
  number: 0
  string: h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_bootstrapping
{% else %}
  # Keep above the number of the _bootstrapping package
  number: 1
{% endif %}
  skip: true  # [not unix]
  script_env:
    - BOOTSTRAPPING={{ bootstrapping }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
{% if bootstrapping != 'yes' %}
    - make
    - libtool  # [unix]
    - pkg-config  # [unix]
  host:
    - zlib
    - openssl  # [unix]
    - libev >=4.11
    - c-ares >=1.7.5
  run:
    - zlib
    - openssl  # [unix]
    - libev >=4.11
    - c-ares >=1.7.5
    - libstdcxx-ng  # [linux]
{% endif %}

outputs:
  - name: libnghttp2
    script: install.sh  # [unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
{% if bootstrapping != 'yes' %}
        - make
      host:
        - zlib
        - openssl  # [unix]
        - libev >=4.11
        - c-ares >=1.7.5
      run:
        - zlib
        - openssl  # [unix]
        - libev >=4.11
        - c-ares >=1.7.5
        - libstdcxx-ng  # [linux]
{% endif %}
    build:
      run_exports:
        - {{ pin_subpackage('libnghttp2') }}
    files:
      - include/nghttp2/nghttp2*  # [unix]
      - lib/libnghttp2*  # [unix]
      - lib/nghttp2*  # [unix]
      - lib/pkgconfig/libnghttp2*  # [unix]
      - bin/nghttp*  # [unix]
    test:
      commands:
{% if bootstrapping != 'yes' %}
        - nghttp -nv https://nghttp2.org
{% endif %}
        - test ! -f ${PREFIX}/lib/lib{{ name }}.a    # [unix]
        - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]

  - name: libnghttp2-static
    script: install.sh  # [unix]
    build:
      skip: true  # [not unix]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
{% if bootstrapping != 'yes' %}
        - make
      host:
        - {{ pin_subpackage('libnghttp2', exact=True) }}
      run:
        - {{ pin_subpackage('libnghttp2', exact=True) }}
        - libev-static
        - c-ares-static
{% endif %}
    test:
      commands:
        - test -f ${PREFIX}/lib/lib{{ name }}.a    # [unix]

about:
  home: http://github.com/nghttp2/nghttp2
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: This is an implementation of Hypertext Transfer Protocol version 2.

  description: |
    This is an implementation of the Hypertext Transfer Protocol version 2 in C.

    The framing layer of HTTP/2 is implemented as a reusable C library. On top
    of that, we have implemented an HTTP/2 client, server and proxy. We have
    also developed load test and benchmarking tools for HTTP/2.
  doc_url: https://nghttp2.org/documentation/
  dev_url: https://github.com/nghttp2/nghttp2

extra:
  recipe-maintainers:
    - cpaulik
    - mariusvniekerk
    - wolfv
